POST {{host-api}}/user/bookings
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "hotelId": "f47ac10b-58cc-4372-a567-0e02b2c3d482",
  "rooms": [
    "9f546671-d9af-4fd4-af26-9c6b19187e8c"
  ],
  "checkIn": "2025-06-28T15:00:00+03:00",
  "checkOut": "2025-06-29T15:00:00+03:00"
}
###
GET {{host-api}}/user/bookings
Authorization: Bearer {{token}}
Content-Type: application/json
###
POST {{host-api}}/user/bookings/135970eb-cfa4-42d6-aad2-08ddb28e5c61/cancel
Authorization: Bearer {{token}}
Content-Type: application/json
###
POST {{host-api}}/user/bookings/5f94a632-37c9-4ef2-1e90-08ddb296fcca/confirm
Authorization: Bearer {{token}}
Content-Type: application/json
###
POST {{host-api}}/user/bookings/5f94a632-37c9-4ef2-1e90-08ddb296fcca/complete
Authorization: Bearer {{token}}
Content-Type: application/json
