GET {{host-api}}/cities
Authorization: Bearer {{token}}
Content-Type: application/json
###
GET {{host-api}}/cities/trending-destinations
Content-Type: application/json
###
GET {{host-api}}/cities/d290f1ee-6c54-4b01-90e6-d701748f0851
Authorization: Bearer {{token}}
Content-Type: application/json
###
POST {{host-api}}/cities
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "London",
  "country": "UK",
  "postOffice": "33300"
}
###
PUT {{host-api}}/cities/7b11747b-30aa-4e33-e757-08ddab8bd0b1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "London",
  "country": "UK",
  "postOffice": "33301"
}
###
DELETE {{host-api}}/cities/7b11747b-30aa-4e33-e757-08ddab8bd0b1
Authorization: Bearer {{token}}
Content-Type: application/json
###
PUT {{host-api}}/cities/d290f1ee-6c54-4b01-90e6-d701748f0851/thumbnail
Authorization: Bearer {{token}}
Content-Type: application/json

"10fd6042-ca29-43ba-723b-08ddb175a566"
