@TravelBooking-API = http://localhost:5144

POST {{TravelBooking-API}}/api/accounts/sign-up
Content-Type: application/json
Accept: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "Password123",
  "confirmPassword": "Password123"
}
###
