@TravelBooking-API = http://localhost:5144
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJmODMwZjZhMS0yZjgwLTRhZWItYjEwNS00NDIyYmUyMTAzMTIiLCJzdWIiOiIyNmI0NmU1MC1kNjg5LTQ2MjgtZGE3Yy0wOGRkYTE1ODBhZDkiLCJlbWFpbCI6IlRvbS5kb2VAZXhhbXBsZS5jb20iLCJyb2xlIjoiVXNlciIsIm5iZiI6MTc0ODkwMDAxMywiZXhwIjoxNzQ4OTAwMzEzLCJpYXQiOjE3NDg5MDAwMTMsImlzcyI6ImxvY2FsSG9zdCJ9.S2k9beQpZJBo8XP343pSe1k6PiH_DGfhhnrujK8KMdQ

POST {{TravelBooking-API}}/api/accounts/sign-up
Content-Type: application/json
Accept: application/json

{
  "firstName": "Tom",
  "lastName": "Doe",
  "email": "Tom.doe@example.com",
  "password": "Password123",
  "confirmPassword": "Password123"
}
###

POST {{TravelBooking-API}}/api/accounts/sign-in
Content-Type: application/json

{
  "email": "Tom.doe@example.com",
  "password": "Password123"
}
###
GET {{TravelBooking-API}}/api/accounts/sign-out
Authorization: Bearer {{token}}

###
GET {{TravelBooking-API}}/api/accounts/sign-out/all-devices
Authorization: Bearer {{token}}
